Enable google monitoring and gitlab runners using dind
craigbehnke/terraform-google-gitlab-docker-autoscaler-runner pull request #8
Opened 2024-03-01 15:10 UTC by Langstra

I dont know why, but github didn't show changes I pushed to the branch. Check here the original comments. https://github.com/craigbehnke/terraform-google-gitlab-docker-autoscaler-runner/pull/7

2024-03-01 19:43 UTC, craigbehnke commented
One more thing on the configuration: the typedef for the root level `var.runners.host_metric_interval` config should be optional, defaulting to 60 (`optional(number,60)`). That way there is no breaking change (I just tried to redeploy with the latest configuration and it failed on me if I didn't edit my config).

2024-03-02 18:16 UTC, craigbehnke requested changes
Please move the `optional(number,60)` type to the `host_metric_interval` variable.

2024-03-02 18:16 UTC, craigbehnke commented on variables.tf
> +    idle_count = optional(number, 60)
This is very dangerous.
e2-highcpu-8 cost = $56.68304/month (VM used in example)
$56.68304 * 60 = $3400.9824/month by default

Please revert this back to `number`.

2024-03-02 18:16 UTC, craigbehnke commented on variables.tf
> +    host_metric_interval = number
Please make the type here for `host_metric_interval` = `optional(number,60)`.

2024-03-04 08:54 UTC, Langstra commented on variables.tf
> +    idle_count = optional(number, 60)
oh wow, I messed this up big time. I reverted this and added it to the host_metric_interval.

2024-03-04 17:28 UTC, craigbehnke approved these changes

2024-03-04 17:37 UTC, merged

2024-03-04 17:37 UTC, craigbehnke commented
Thank you very much, @Langstra!